// Sample trivia questions - this would be expanded with real questions
module.exports = [
    {
        id: 1,
        text: "What is the capital of France?",
        correctAnswer: "Paris",
        options: [
            "Paris",
            "London",
            "Berlin",
            "Madrid",
            "Rome",
            "Vienna",
            "Athens",
            "Amsterdam",
            "Brussels",
            "Lisbon",
            "Dublin",
            "Warsaw",
        ],
        category: "Geography",
    },
    {
        id: 2,
        text: "Which planet is known as the Red Planet?",
        correctAnswer: "Mars",
        options: [
            "Mars",
            "Venus",
            "Jupiter",
            "Mercury",
            "Saturn",
            "Neptune",
            "Uranus",
            "Pluto",
            "Earth",
            "Ceres",
            "Eris",
            "Makemake",
        ],
        category: "Astronomy",
    },
    {
        id: 3,
        text: 'Which element has the chemical symbol "O"?',
        correctAnswer: "Oxygen",
        options: [
            "Oxygen",
            "Gold",
            "Silver",
            "Iron",
            "Carbon",
            "Hydrogen",
            "Nitrogen",
            "Helium",
            "Neon",
            "Sodium",
            "Potassium",
            "Calcium",
        ],
        category: "Chemistry",
    },
    {
        id: 4,
        text: "Who painted the Mona Lisa?",
        correctAnswer: "Leonardo da Vinci",
        options: [
            "Leonardo da Vinci",
            "Pablo Picasso",
            "Vincent van Gogh",
            "Michelangelo",
            "Rembrandt",
            "Claude Monet",
            "Salvador Dalí",
            "Raphael",
            "Johannes Vermeer",
            "Andy Warhol",
            "Frida Kahlo",
            "Sandro Botticelli",
        ],
        category: "Art",
    },
    {
        id: 5,
        text: "Which country has the largest population in the world?",
        correctAnswer: "China",
        options: [
            "China",
            "India",
            "United States",
            "Indonesia",
            "Pakistan",
            "Brazil",
            "Nigeria",
            "Bangladesh",
            "Russia",
            "Mexico",
            "Japan",
            "Ethiopia",
        ],
        category: "Geography",
    },
    // Add more questions as needed
];
