// Sample puzzle maps
module.exports = [
    {
        id: 1,
        name: "Tutorial Level",
        width: 10,
        height: 10,
        layout: [
            "##########",
            "#        #",
            "# O  O   #",
            "#    #   #",
            "#   ##   #",
            "#    #   #",
            "#        #",
            "#   O  O #",
            "#        #",
            "##########",
        ],
        startingPositions: [
            { x: 2, y: 2 },
            { x: 5, y: 2 },
            { x: 2, y: 7 },
            { x: 5, y: 7 },
            { x: 7, y: 5 },
        ],
        objectives: [
            { x: 7, y: 2 },
            { x: 2, y: 5 },
            { x: 7, y: 7 },
            { x: 5, y: 5 },
            { x: 2, y: 1 },
        ],
        obstacles: [
            { x: 5, y: 3 },
            { x: 5, y: 4 },
            { x: 5, y: 5 },
            { x: 6, y: 4 },
        ],
    },
    {
        id: 2,
        name: "Maze Runner",
        width: 12,
        height: 12,
        layout: [
            "############",
            "#          #",
            "# ######## #",
            "# #      # #",
            "# # #### # #",
            "# # #    # #",
            "# # # #### #",
            "# # #    # #",
            "# # #### # #",
            "# #      # #",
            "# ######## #",
            "############",
        ],
        startingPositions: [
            { x: 1, y: 1 },
            { x: 10, y: 1 },
            { x: 1, y: 10 },
            { x: 10, y: 10 },
            { x: 6, y: 6 },
        ],
        objectives: [
            { x: 10, y: 10 },
            { x: 1, y: 10 },
            { x: 10, y: 1 },
            { x: 1, y: 1 },
            { x: 6, y: 1 },
        ],
        obstacles: [
            // Wall obstacles (too many to list individually)
            // These would be generated from the layout
            { x: 2, y: 2 },
            { x: 3, y: 2 },
            { x: 4, y: 2 },
            { x: 5, y: 2 },
            { x: 6, y: 2 },
            { x: 7, y: 2 },
            { x: 8, y: 2 },
            { x: 9, y: 2 },
            // ...more obstacles based on the maze walls
        ],
    },
    {
        id: 3,
        name: "Cross Roads",
        width: 10,
        height: 10,
        layout: [
            "##########",
            "#        #",
            "#  ####  #",
            "#  #  #  #",
            "#  #  #  #",
            "#  #  #  #",
            "#  #  #  #",
            "#  ####  #",
            "#        #",
            "##########",
        ],
        startingPositions: [
            { x: 1, y: 1 },
            { x: 8, y: 1 },
            { x: 1, y: 8 },
            { x: 8, y: 8 },
            { x: 5, y: 5 },
        ],
        objectives: [
            { x: 8, y: 8 },
            { x: 1, y: 8 },
            { x: 8, y: 1 },
            { x: 1, y: 1 },
            { x: 5, y: 1 },
        ],
        obstacles: [
            // Central cross shape obstacles
            { x: 3, y: 3 },
            { x: 4, y: 3 },
            { x: 5, y: 3 },
            { x: 6, y: 3 },
            { x: 3, y: 4 },
            { x: 6, y: 4 },
            { x: 3, y: 5 },
            { x: 6, y: 5 },
            { x: 3, y: 6 },
            { x: 6, y: 6 },
            { x: 3, y: 7 },
            { x: 4, y: 7 },
            { x: 5, y: 7 },
            { x: 6, y: 7 },
        ],
    },
];
